import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white flex flex-col`}
      >
        <div className="p-5 sticky top-0 bg-white w-full flex justify-center">
          <div className="w-[65%] flex justify-between self-center">
            <a href="" className="font-bold text-green-400">Vincent Jonathan</a>
            <div className="flex justify-evenly w-[30rem]">
              <a href="#beranda" className="text-slate-500">Beranda</a>
              <a href="#tentang-saya" className="text-slate-500">Tentang Saya</a>
              <a href="#portfolio" className="text-slate-500">Portfolio</a>
              <a href="#clients" className="text-slate-500">Clients</a>
              <a href="#blog" className="text-slate-500">Blog</a>
              <a href="#contact" className="text-slate-500">Contact</a>
            </div>
          </div>
        </div>
        {/* <div className="flex bg-slate-600 justify-evenly text-white py-3">
          <p className="hover:font-bold hover:cursor-pointer">Product List</p>
          <p className="hover:font-bold hover:cursor-pointer hover:text-red-500">Log Out</p>
        </div> */}
        {children}
      </body>
    </html>
  );
}
